fsnotify.go, fsnotify_test.go
As a user of the library I want to use `Op.String()` to classify events by their op string without the need to parse `event.String()` or creating my own string builder.
The change delegates string representation of the event to the `Op` receiver, as suggested by a few people before.
Tested on Linux and Darwin.
`
$ go test
PASS
ok  	github.com/fsnotify/fsnotify	13.581s
`
Signed the CLA.
=> Add a String() func to Event.Op

inotify_test.go
this addresses the comments in ~~#117~~ #174:
- the errChan buffer is necessary to ensure the file generation goroutine does not get block by the main test goroutine
- got rid of the sleeps in the file generation goroutine (reduce test time by a few seconds on my laptop)
- create files based on a fixed number instead of a fixed amount of time
edit: fixes #142 #150
=> deflake inotify stress test

inotify.go
resolves #155
(originally from #174)
=> Create inotify fd with close-on-exec

fsnotify.go, inotify.go, inotify_test.go
Upon receiving an event with IN_Q_OVERFLOW set in the mask, generate an
error on the Errors chan, so that the application can take appropriate
action.
=> Properly handle inotify's IN_Q_OVERFLOW event

.travis.yml
two most recent stable versions + tip
=> ci: update for Go 1.8

inotify.go
This PR fixes two potential problems in Watch.Add in `inotify.go`:
* Race when `Add()` is called concurrently.
* Incorrect `flags` stored when `InotifyAddWatch` fails.
In addition, it re-uses the existing watch entry when modifying an existing watch.
The individual commits contain more details.
=> Watch.Add improvements (avoid race, fix consistency, reduce garbage)

inotify.go, inotify_test.go
This resolves a fairly common and easy to hit deadlock that occurs in inotify/linux. The issues reported are quoted below.
Commit message follows:
> Several people have reported this issue where if you are using a
> single goroutine to watch for fs events and you call Remove in
> that goroutine it can deadlock. The cause for this is that the Remove
> was made synchronous by PR #73. The reason for this was to try and
> ensure that maps were no longer leaking.
> 
> In this PR: IN_IGNORE was used as the event to ensure map cleanup.
> This worked fine when Remove() was called and the next event was
> IN_IGNORE, but when a different event was received the main goroutine
> that's supposed to be reading from the Events channel would be stuck
> waiting for the sync.Cond, which would never be hit …
=> Fix deadlock in Remove (linux/inotify)

inotify_test.go
* Queued inotify events could have been read by the test before max_queued_events was hit
Fixes a race condition in the TestInotifyOverflow test
Pretty small change
go test -run TestInotifyOverflow -count 10 on a multicore machine
=> Fix TestInotifyOverflow

integration_darwin_test.go, integration_test.go
The documentation for t.FailNow (which is called by t.Fatalf) states
that it should not be called in go routines outside of the test go
routine.
no.
=> [#234] t.Fatalf -> t.Errorf in go routines

example_test.go
This PR is just about adding a check for closed channels to the example https://github.com/fsnotify/fsnotify/blob/master/example_test.go
Without that check the goroutine will keep printing empty errors (nils) & events after the watcher is closed.
See https://github.com/fsnotify/fsnotify/issues/229
=> Check if channels are closed in the example

.travis.yml, fsnotify.go
- Changes travis config to only run golint on latest go version
- Adds 1.11 and 1.12 to to the go version list to test against
Does CI pass?
Does golint run on go1.12?
N/A
Fixes #275
Closes #271
=> only run golint on latest version of go

inotify_poller.go
* Add the unix.O_CLOEXEC to the Pipe2 call
* Add unix.EPOLL_CLOEXEC to the Epoll call
I've signed the CLA.
When creating a fsnotify.NewWatcher(), four file descriptors are opened: One for inotify, one for epoll and two for the two ends of a pipe. Only the inotify one has CLOEXEC set. This PR adds the CLOEXEC flag to all four file descriptors, preventing a leak in cases where execve is used e.g. to reload an executable on code change.
I read the manpages of pipe2 and epoll_create2 to get an idea of the flags.
In a simple program which just opens a NewWatcher, does a syscall.Exec, and sleeps, the difference in the number of open file descriptors is visible in /proc/<pid>/fd/
=> Also create epoll and pipe fds with close-on-exec (#155)

inotify.go
Fix the following unsafe pointer conversion found using the Go 1.14
`-d=checkptr gcflags` (`go1.14rc1 test -gcflags=all=-d=checkptr -v ./...`)
```
fatal error: checkptr: unsafe pointer conversion
goroutine 68 [running]:
runtime.throw(0x5833e9, 0x23)
runtime/panic.go:1112 +0x72 fp=0xc00030fba8 sp=0xc00030fb78 pc=0x432a32
runtime.checkptrAlignment(0xc00031f018, 0x544800, 0x1)
runtime/checkptr.go:18 +0xb7 fp=0xc00030fbd8 sp=0xc00030fba8 pc=0x4063a7
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0002900f0)
github.com/fsnotify/fsnotify/inotify.go:275 +0x457 fp=0xc00031ffd8 sp=0xc00030fbd8 pc=0x519037
runtime.goexit()
runtime/asm_amd64.s:1375 +0x1 fp=0xc00031ffe0 sp=0xc00031ffd8 pc=0x463eb1
created by github.com/fsnotify/fsnotify.NewWatcher
github.com/fsnotify/fsnotify/inotify.go:59 …
```
=> Fix unsafe pointer conversion

.github/workflows/test.yml
Remove 1.11 (and comments about 1.10 and 1.9) from the the GitHub actions testing matrix.
See #379 where the fact that 1.11 is no longer supported becomes an issue for pulling in new features in the latest versions of x/sys/unix.
N/A
=> Drop support/testing for Go 1.11 and earlier

go.mod, go.sum
Upgrades x/sys to the latest revision as of today.
This update appears to break test `(macos-latest, 1.11)`.
#371 will require an update to x/sys and exhibits the same test failure.
This PR demonstrates that the breakage is from x/sys, not the content of #371.
I don't know if it's safe to drop support for 1.11, if this represents a bug somehow introduced into x/sys/unix, or something else.
The important test failure is automated with GitHub actions.
=> Update x/sys to latest

README.md, fen.go, fsnotify.go, fsnotify_test.go, inotify.go, inotify_test.go, integration_test.go, kqueue.go, windows.go
This is a minor† change for #199 which on the surface adds a `AddRaw` method to the public interface which does not resolve symlinks before starting a watch.
A follow on from this would be to offer a high level interface as mentioned on my initial comment for the issue - this can be tracked in a separate issue+PR.
† this does change the behaviour of `Add` on windows as it didn't follow symlinks (which do exist) before, but now it does
=> Add AddRaw method which does not follow symlinks

.mailmap, AUTHORS, CHANGELOG.md
After #289 is merged this could be merged and tagged (maybe with a new date)
=> v1.5.0 prep

README.md, fen.go, fsnotify.go, fsnotify_test.go, inotify.go, inotify_test.go, integration_test.go, kqueue.go, windows.go
Revert #289 to resolve regressions in #390 #393 #389.
We can give it another go. @Code0x58.
`go test`
=> Revert Add AddRaw to not follow symlinks

inotify_poller_test.go, inotify_test.go, integration_test.go
fixes `go vet` warnings:
```
./inotify_poller_test.go:182:5: call to (*T).Fatalf from a non-test goroutine
./inotify_test.go:341:4: call to (*T).Fatalf from a non-test goroutine
./integration_test.go:80:4: call to (*T).Fatalf from a non-test goroutine
./integration_test.go:843:4: call to (*T).Fatalf from a non-test goroutine
```
closes https://github.com/fsnotify/fsnotify/issues/412
Read https://github.com/fsnotify/fsnotify/issues/412 and https://github.com/fsnotify/fsnotify/pull/414 to understand the problem and make sure `testing.T` is correctly used.
Run `go vet` locally.
=> fix go vet warnings: call to (*T).Fatalf from a non-test goroutine

.github/workflows/build.yml
This creates a Github action to run cross-compilation
builds for all supported targets (or at least that's the idea)
This would have caught #389 and should
catch build failures for supported targets.
The output of the builds
N/A
=> Run cross-compilation builds on every push

inotify_poller.go
In `newEmptyPoller` when creating the `poller` using `newEmptyPoller(fd)`, the
`fd` field is already set. There is no need to set it again.
=> Don't set `poller.fd` twice in `newFdPoller`

.github/workflows/test.yml
I imagine that disabling testing for PRs may have been needed to unbreak things while cleaning up the older releases in the test matrix.
It would be good to re-enable tests on PRs.
=> Re-enable tests for PRs

integration_test.go
When testing the FEN code repeatedly and under
system load I can sometimes get these tests to fail
with a missed WRITE event. With these longer sleeps
I have been unable to produce any test failures.
This is unashamedly in support of #12 / #371
Additionally, this PR gives slightly more friendly names to the sleep durations based on their purposes.
Is there any good reason not to do this? It seems reasonable to me and
it prevents spurious test failures.
N/A
=> Integration Tests: change 1ms sleeps to 50ms

.github/workflows/test.yml
=> Add FreeBSD testing in Github Actions (fix #389)

fsnotify_unsupported.go
In cases where fsnotify is a transitive dependency of a package, it
might need to be built on platforms not supported (yet), e.g. aix.
Provide an empty implemention for these cases, so depending packages
don't need to add workarounds.
Replaces #314
=> Allow build on unsupported GOOS

README.md
Also add a link to the `syscall` package and remove some trailing
whitespaces.
=> README.md: link to pkg.go.dev for golang.org/x/sys package

CHANGELOG.md, go.mod
* Update Changelog
* Retracted v1.5.3
please read https://github.com/fsnotify/fsnotify/issues/445#issuecomment-1108326388
-----
After merging, I'm going to create `v1.5.4` tag on the main branch, and force update `v1.5.3` to https://github.com/fsnotify/fsnotify/commit/a83458b875bd39c6c17de39f77328d4dc5dd88c7
=> Prepare for v1.5.4

windows.go
isClosed may be read and modified concurrently on Windows if the Watcher is closed at the same time as a new entry being added. This change protects isClosed to prevent race conditions.
The order of fields for the Windows Watcher have been rearranged to group fields protected by the mutex together to make it easier for reviewers to understand at a glance which fields are expected to be accessed through the mutex.
=> windows: protect access to isClosed with mutex

fsnotify.go, inotify.go, inotify_test.go, kqueue.go, windows.go
Applies https://github.com/shogo82148/fsnotify/pull/8 to replace #455.
---
The errors returned by the various implementations of the watcher are all different
which makes handling them difficult. This PR follows the suggestion in:
https://github.com/fsnotify/fsnotify/pull/455#issuecomment-1146037157 by @mattn
to create a common error which is wrapped by the implementations.
Replaces: https://github.com/fsnotify/fsnotify/pull/455
Signed-off-by: Andrew Thornton <art27@cantab.net>
=> Use common error when removing an unwatched file

windows.go
Fixes a locking issue in Windows
While `defer` is usually ideal for these situations, due to how some goroutines may be reading events sent to channels before the function returns I think explicit (un)locking for this specific case may be required.
Tested the GH actions over at https://github.com/jolheiser/fsnotify/pull/1
=> Windows explicit (un)lock

fsnotify.go
It replaces bytes.Buffer with strings.Builder in the String() method for Op.
There is only one file changes and the only change is that bytes.Buffer is replaces with strings.Builder as since go 1.10 this is the recommended most efficient way of building a String.
Anything that prints out an Op.
=> strings.Builder instead of bytes.Buffer [Go 1.10+]

kqueue.go
Fixes a performance problem in the kqueue-based implementation of watcher.
In the old implementation, watcher.Close() would clone the list of watches, then run Remove. Each run of Remove would also iterate over the full list of watches.
This indexes the watches better so that Remove doesn't need to iterate over the full list.
There should be no functional changes in this PR
=> kqueue: Make watcher.Close() O(n) instead of O(n^2)

inotify.go, inotify_test.go
Currently fsnorify suppresses a Chmod event if the file does not exist
when the event is received.
This makes it impossible to use fsnotify to detect when an opened
file is removed. In such case the Linux kernel sends IN_ATTRIB event,
as described in inotify(7) man page:
> IN_ATTRIB (*)
>        Metadata  changed—for example, permissions (e.g., chmod(2)),
>        timestamps (e.g., utimensat(2)), extended attributes  (setx‐
>        attr(2)), link count (since Linux 2.6.25; e.g., for the tar‐
>        get of link(2) and for unlink(2)), and user/group ID  (e.g.,
>        chown(2)).
(in this very case it's link count that changes).
To fix:
* Modify the code to only suppress MODIFY and CREATE events.
* Add a test case to verify Chmod event is delivered.
While at it, fix the comment in …
=> Do not suppress Chmod on non-existent file

README.md
Hey there, after debugging an issue within another project I found out that `fs.inotify.max_user_instances` also has influence on the watcher creation. I verified that with a small test tool like this:
```go
package main
import (
"fmt"
"github.com/fsnotify/fsnotify"
)
func main() {
count := 0
for {
_, err := fsnotify.NewWatcher()
if err != nil || count > 999 {
fmt.Println(err)
break
}
count += 1
}
fmt.Printf("count == %v", count)
}
```
Reaching the 1000 watchers was not possible by adapting only `fs.inotify.max_user_watches`, but with modifying `fs.inotify.max_user_instances` it worked. I updated the documentation for that scenario.
=> Update documentation for linux systems (max_user_watches)

README.md
Currently the README links to the CONTRIBUTING file on the `master` branch, while the default branch is now `main`.  
There have only been minor changes, but `main` is the current version.
=> Update link to CONTRIBUTING in the README

README.md
It already mentioned NFS, but also mention SMB. Also rename "OS X" to "macOS" while I'm at it.
=> Clarify README on network drives

.github/workflows/Vagrantfile.debian6, .github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/test.yml, .github/workflows/vagrant.yml, README.md, integration_test.go
- Test all GOOS/GOARCH combinations by looping over "go tool dist list";
this just tests if it compiles.
- Add a Vagrant box to test Debian 6 / Linux 2.6.32; this was adapted
from @horahoradev's patch at https://github.com/fsnotify/fsnotify/pull/434.
- Update the minimum version requirements: we test Linux 2.6.32 now and
turns out that's also the minimum version [Go supports] in recent
releases, so just set it to that.
Need Go 1.16 for retract in go.mod. I don't know, maybe we can just
remove the retract? Latest Debian ships with Go 1.15.
[Go supports]: https://github.com/golang/go/issues/45964
- Test both Go 1.16 and 1.18 (the lowest supported version and newest
version). I guess we could also test 1.17, but the CI already takes
somewhat long and I can't recall ever having a situation …
=> Test some more things in CI

kqueue.go
kqueue requires opening a file descriptor for every file; so we read the
directory and do that. If this failed the error was quite unclear; for
example:
"/tmp/fsnotify_permission_denied/": permission denied
This puts the filepath in there:
"/tmp/fsnotify_permission_denied/": "/tmp/fsnotify_permission_denied/test2.log": permission denied
Fixes #270
=> kqueue: better error if watching a file fails

README.md, cmd/fsnotify/main.go
This adds a little example that can be run:
% go run ./cmd/fsnotify **/*
12:76:11.4710 watching; press ^C to exit
12:76:13.6549   1 REMOVE                "cmd/fsnotify/4913"
12:76:13.6550   2 RENAME                "cmd/fsnotify/main.go"
12:76:13.6550   3 RENAME                "cmd/fsnotify/main.go"
12:76:13.6612   4 CREATE                "cmd/fsnotify/main.go"
12:76:13.6612   5 WRITE      (modified) "cmd/fsnotify/main.go"
12:76:13.6614   6 WRITE      (modified) "cmd/fsnotify/main.go"
12:76:13.6648   7 CHMOD                 "cmd/fsnotify/main.go"
12:76:15.2919   8 CREATE                "cmd/fsnotify/4913"
12:76:15.2919   9 REMOVE                "cmd/fsnotify/4913"
12:76:15.2922  10 CHMOD                 "cmd/fsnotify/main.go"
12:76:15.2923  11 REMOVE                "cmd/fsnotify/main.go" …
=> Add cmd/fsnotify

inotify.go
This is quite an odd check, leading to an inconsistent event stream,
which also doesn't match what other platforms do. If you do a "CREATE +
MODIFY + REMOVE" in quick succession then you probably *want* all three
events. If you don't want to operate on non-existing files, then you can
check this in your application code.
You need to do that already, since this check is far from reliable. In
the time between this check and the application code doing something
with an event the file may have been deleted already.
I looked a bit at the history of this, and looks like it was added in
2013 with cc2c34e; issue 36 refers to this issue on the old repo, which
mentions it fixes a memory leak: https://github.com/howeyc/fsnotify/issues/36
I can't reproduce that at all; using the CLI from #463 …
=> inotify: don't ignore events for files that don't exist

.github/workflows/vagrant.yml
The ./cmd/fsnotify doesn't have any tests, but sooner or later we'll
have subpackages so deal with it properly now.
=> debian 6 test: deal with multiple packages

kqueue.go
Retry the unix.Open() if the error returned is EINTR; looking around the
web it seems many systems handle it like this. This is also what
os.Open() does:
https://github.com/golang/go/commit/50d0ee0c98ea21f818d2daa9bc21ef51861a2ef9
Fixes #354
NOTE: Please do not open a pull request that adds or changes the public API without giving consideration to all supported operating systems.
=> macos: retry if open() returns EINTR

README.md, cmd/fsnotify/main.go, fsnotify.go
Using:
if event.Op&fsnotify.Create == fsnotify.Create {
}
is overly verbose and awkward; a Has() method makes this much nicer:
if event.Has(fsnotify.Create) {
}
PR #76 was previously rejected; I think that HasCreate() etc. is
overkill, but a Has() method makes the library quite a bit more
convenient IMO.
I added it to both the Event and Op to avoid confusion; with this we can
change the Op field to be private in a future v2.
Fixes #107
=> Add {Event,Op}.Has()

fsnotify.go, fsnotify_test.go, helpers_test.go, inotify.go, inotify_test.go, integration_darwin_test.go, integration_test.go, kqueue.go
This rewrites quite a lot of tests to be much more easily readable.
While working on #472 I wanted to check "how do renames behave now?",
and found this quite hard as most test cases were >90% "plumbing", and
seeing "what file operations does this do?" and "what events do we get?"
was not very easy.
So refactor the lot, based on some work I did in #472:
- Add a bunch of "shell-like" helper functions so you're not forever
typing error checks, filepath.Join(), and eventSeparator(). Just
touch(t, tmp, "file") will create a file in tmp.
- Add eventCollector type which will collect all events in in a slice,
replacing the previous "counter". This also ensures that the Watcher
is closed within a second (this removes a lot of duplicate code).
This is also much more precise than merely counting …
=> Rewrite tests

helpers_test.go, integration_test.go, windows.go
=> Fix: Update watch paths when renaming directories with sub-watches on Windows 

integration_test.go, windows.go
when i remWatch a directory using remWatch, and then delete the directory ,and i find the directory is still in there but i can't access because a handle is still open
see #42 ,the gist by timshannon  (https://gist.github.com/timshannon/603f92824c5294269797)
=> [bugfix] close handle when remWatch open in getIno

.github/workflows/build.yml, .github/workflows/staticcheck.yml, .github/workflows/test.yml, .github/workflows/vagrant.yml, .gitignore, go.mod, go.sum
We need to update x/sys to support GOARCH=loong64, which is new in Go
1.19.
Also kick off fewer builds; they regularly get hung in the queue as we
have quite a few test jobs now.
=> ci: update to use Go 1.19, kick off fewer builds, update x/sys

windows.go
People are running in to trouble because the 4K buffer can overflow;
see: #72.
This is not a "real" fix, but I think a 64K buffer is acceptable even on
memory-limited machines; no one is running the Windows on an Arduino,
and even with something like 128M of memory, the extra 124K is basically
negligible. There is also no real performance difference between
allocating a large array vs. a small array: they're both comparable.
It should probably be enough for most applications. Need to look in the
future to either dynamically grow the size, or allow setting it similar
to what tilt does as mentioned in #72.
=> windows: increase buffer size from 4K to 64K

helpers_test.go, integration_test.go, kqueue.go
This was added in 00f2dfd (2011): "BSD Test: Need to use outside program
to trigger some events". All tests pass fine with just os.Rename(), so
just use that.
Might add another real-world test in the future for common tools like
mv, cp, vi, etc. because they don't always behave the same as library
calls, but calling mv in *only* the mv() helper is rather odd.
This also renames a few things in the kqueue backend for clarity, and
uses map[string]struct{} if we just use them for lookups to an
allocation (I originally tried to fix #488, but gave up on that for now,
hence the kqueue changes).
=> Use "os.Rename()" in tests instead of "mv"

inotify.go, integration_test.go
This Skip() was added in 2013 (c825c6d) with "Windows cannot overwrite
file on rename", but it seems to work fine. os.Rename() is also
documented as "If newpath already exists and is not a directory, Rename
replaces it", so if it *doesn't* work it's a bug in os.Rename(). Maybe
os.Rename() behaved different nine years ago.
=> windows: run TestWatchRename/rename_overwriting_existing_file

helpers_test.go, integration_test.go
Symlinks are supported since Windows Vista; there's no reason to not
test it.
=> windows: test symlinks

.github/workflows/test.yml, integration_test.go, internal/unix.go, internal/windows.go, kqueue.go
Watching an entire directory would fail if it contains a file we can't
read due to permission errors. That's obviously not ideal, so just skip
the file.
Also add a test for trying to watch a directory where the permissions
are denied, and test the error is what's expected; this prevents
regressions like in #393.
Fixes #439
=> kqueue: don't set up watchers on unreadable files

CHANGELOG.md, backend_fen.go, backend_inotify.go, backend_kqueue.go, backend_other.go, backend_windows.go, fsnotify.go, fsnotify_test.go, mkdoc.zsh
Also consistently return nil for Remove() and WatchList(). For Remove() we could return an error, but I don't really see the point: if the watcher is closed it's basically a no-op so returning nil is fine.
For WatchList() I'd like to return an error, but there is no error return, so explicitly returning nil is the best we can do.
Fixes #511
=> Return ErrClosed on Add() when the watcher is closed

CHANGELOG.md, backend_fen.go, backend_inotify.go, backend_kqueue.go, backend_other.go, backend_windows.go, fsnotify_test.go, mkdoc.zsh
Renaming a watched path is problematic; on inotify we just get a IN_MOVED_SELF event with the old filename and that's it; no more events for you! So if you do:
watch one
mv    one two
echo  asd >two
You still continue to get events for the file "one", even though it's now named "two" (the file descriptor doesn't care about the rename). There is no way we can know the new event as far as I can tell, inotifywait(1) also behaves like this. So instead of continuing in a semi-broken state just remove the watcher, like we do for deletes.
On kqueue and FEN the situation is similar, and we actually already removed watchers on renames.
On Windows this all works nicely; the watch is preserved and the filename is updated. I decided to keep this as-is for now, even though it's inconsistent. We …
=> inotify: remove watch when renaming a watched path

backend_windows.go, backend_windows_test.go, fsnotify_test.go
On Windows a FILE_ACTION_MODIFIED event (i.e. a Write event) is triggered on file attribute changes, rather than some dedicates ATTRIBUTE_CHANGED event. Looking at the docs, I don't really see a way to distinguish between "real" write events and attribute changes. This is very odd, but seems to be how the ReadDirectoryChangesW() API works.
The only way I can see to distinguish between the two events is to set up two filters: one with a FILE_NOTIFY_CHANGE_ATTRIBUTES, and one without. But that seems overly complex, and no one asked to get Chmod events for Windows; it's not really all that interesting on Windows anyway.
The problem is that some software (anti-virus, backup software, etc.) can issue lots of attribute changes, causing a lot of "fake" Write events.
So remove the …
=> windows: ignore file attributes

CHANGELOG.md, backend_fen.go, backend_inotify.go, backend_kqueue.go, backend_windows.go, fsnotify.go, mkdoc.zsh
Extracted from #521; we want to do this no matter what.
Fixes #383
=> windows: use ErrEventOverflow instead of "short read in readEvents()"

backend_kqueue.go, fsnotify_test.go, test/kqueue.c
The problem was that that on Delete events for directories it would call Watcher.Remove() for all files in that directory too. This is fine if you call w.Remove() from the application, but if you rm -rf a directory the directory itself tends to be the first remove event (on FreeBSD at least):
DELETE WRITE  /tmp/xxx
DELETE        /tmp/xxx/a
DELETE        /tmp/xxx/b
DELETE        /tmp/xxx/c
DELETE        /tmp/xxx/d
DELETE        /tmp/xxx/e
DELETE        /tmp/xxx/f
DELETE        /tmp/xxx/g
So what would happen is that the internal state for /tmp/xxx/a etc. would get removed, and when the event gets processed we no longer have access to it.
Move Remove() to remove() with a flag to control removing files. If a watched directory is removed then the files will emit their own delete event, so we …
=> kqueue: don't immediately remove watches for all files in a directory on Delete event

.circleci/config.yml, .github/workflows/build.yml, .gitignore, backend_other.go, internal/debug_openbsd.go
Use CircleCI to add CI for this.
Fixes #136
=> Add CI for linux/arm64, darwin/arm64

fsnotify_test.go, internal/unix.go, internal/unix2.go, internal/windows.go
Tests for symlink always fail when run the tests as non-admin users on Windows since Windows require privileges to create symlinks. This CL change to check the privileges.
(Can I put label `hacktoberfest-accepted` on this PR ?)
=> Check privileges for symlink tests on Windows

backend_fen.go, backend_inotify.go, backend_kqueue.go, backend_other.go, backend_windows.go, fsnotify.go, mkdoc.zsh
This is similar to Add(), except that you can pass options. Ideally this should just be Add(), but that's not a compatible change, so we're stuck with this until we do a v2.
There are quite a few enhancements that depend on *some* way to pass options; as an example I added WithBufferSize() to control the buffer size for (see #72) for the Windows backend, because that one is fairly trivial to implement:
w, err := fsnotify.NewWatcher()
err = w.AddWith("/path", fsnotify.WithBufferSize(65536*4))
Some other options we might want to add:
err = w.AddWith("/path",
fsnotify.WithEvents(fsnotify.Open | fsnotify.Close),  // Filter events
fsnotify.WithPoll(10*time.Duration),                  // Use poll watcher
fsnotify.WithFanotify(),                              // Prefer fanotify on Linux …
=> Add AddWith() to pass options, allow controlling Windows buffer size

backend_inotify_test.go
This test checks if no additional OS threads are created; this was added after the old epoll-based inotify code was removed (which would create additional threads). It's always been a bit flaky: it currently already runs the test twice and "fails" only if both fail.
We don't really control the Go scheduler and when it creates/destroys OS threads, or have all that much insight in it (the "threadcreate" profile in pprof has been broken for years). I tried to make this test a bit more reliable a few months ago, and the run-it-twice "solution" was the best I could come up.
It still causes some failures though; see the links below. I don't know why it consistently fails on armle (and not e.g. arm64), but that seems a Go thing, rather than a fsnotify thing.
I'm not sure if this test adds all …
=> Remove TestInotifyNoBlockingSyscalls

.cirrus.yml, .github/workflows/test.yml, CHANGELOG.md, backend_kqueue.go
Fix regression from #526, which would sometimes fail with something along the lines of:
--- FAIL: TestWatchRm/remove_watched_directory (1.30s)
helpers_test.go:384: fsnotify.sendDirectoryChangeEvents: open /tmp/TestWatchRmremove_watched_directory2055111636/001: no such file or directory
fsnotify_test.go:750:
have:
REMOVE               "/a"
REMOVE               "/b"
REMOVE               "/c"
REMOVE               "/d"
REMOVE               "/e"
REMOVE               "/f"
REMOVE               "/g"
want:
REMOVE               "/"
REMOVE               "/a"
REMOVE               "/b"
REMOVE               "/c"
REMOVE               "/d"
REMOVE               "/e"
REMOVE               "/f"
REMOVE               "/g"
REMOVE               "/h"
REMOVE               "/i"
REMOVE               "/j"
We can just …
=> kqueue: fix removing a directory

.github/workflows/staticcheck.yml, CHANGELOG.md, backend_kqueue.go, backend_windows.go, internal/freebsd.go, internal/internal.go, internal/unix.go
This fixes a few small staticcheck issues; turns out that staticcheck only compiles the files for the current GOOS:
https://staticcheck.io/docs/running-staticcheck/cli/build-tags/
You can run all systems with:
staticcheck -matrix <<EOF
windows: GOOS=windows
linux: GOOS=linux
freebsd: GOOS=freebsd
openbsd: GOOS=openbsd
netbsd: GOOS=netbsd
darwin: GOOS=darwin
illumos: GOOS=illumos
EOF
The CI runner doesn't really support that, but it's little more than a small wrapper around "go install" with some variables, so just use that directly instead of the action.
=> A few staticcheck fixes

CHANGELOG.md, backend_fen.go, backend_inotify.go, backend_inotify_test.go, backend_kqueue.go, backend_other.go, backend_windows.go, fsnotify.go, fsnotify_test.go, helpers_test.go, mkdoc.zsh
Recursive watches can be added by using a "/..." parameter, similar to the Go command:
w.Add("dir")         // Behaves as before.
w.Add("dir/...")     // Watch dir and all paths underneath it.
w.Remove("dir")      // Remove the watch for dir and, if
// recursive, all paths underneath it too
w.Remove("dir/...")  // Behaves like just "dir" if the path was
// recursive, error otherwise (probably
// want to add recursive remove too at some
// point).
The advantage of using "/..." vs. an option is that it can be easily specified in configuration files and the like; for example from a TOML file:
[watches]
dirs = ["/tmp/one", "/tmp/two/..."]
Options for this were previously discussed at:
https://github.com/fsnotify/fsnotify/pull/339#discussion_r788246013
This should be expanded to other backends …
=> Add recursive watcher for Windows backend

backend_inotify.go, backend_inotify_test.go, fsnotify_test.go
Create a new watches type to keep track of the watches instead of keeping two maps on the Watcher and accessing these directly.
This makes the bookkeeping a bit easier to follow, and we no longer need to worry about locking map access as the watcher type takes care of that now.
Came up in #472 where I want to keep track if a path was added recursively, and this makes that a bit easier.
Also seems a bit faster:
BenchmarkWatch-2          903709              7122 ns/op             194 B/op          3 allocs/op
BenchmarkWatch-2          923980              6322 ns/op             196 B/op          3 allocs/op
Although that benchmark is very simple and only tests one code path; just want to make sure it's not a horrible regression.
=> inotify: simplify bookkeeping of watched paths

fsnotify_test.go, helpers_test.go
Previously it would create all the files and then remove it; remove the file immediately instead.
My /tmp has ~500k free inodes and it will try to create >1 million files, so it will error out on that.
=> Remove file immediately in TestWatchStress

backend_fen.go, backend_inotify.go, backend_kqueue.go, backend_other.go, backend_windows.go, fsnotify_test.go, mkdoc.zsh
Seems like this doesn't return an error with any backend. Maybe it
should, but we can't really change it because it's not compatible. I
tested with v1.5.4 and v1.4.8 too to make sure it's not a recent
regression, and it behaves identical there too.
Fixes #548
=> Test adding a path more than once; update documentation

.github/workflows/build.yml, .github/workflows/test.yml, CHANGELOG.md, go.mod
I have no idea if anyone is using Go 1.16 with fsnotify.
Go 1.16 (released August 2021) became mandatory with v1.5.1 (August 2021). Go 1.17 was released just a few days before it was tagged. Some people did experience problems (#400), but overall the feedback was limited.
So based on this, I think it's probably safe to just follow the Go release policy: "Each major Go release is supported until there are two newer major releases."
This will allow merging #554
=> Update CI to Go 1.17 - 1.20

.circleci/config.yml
Was still using Go 1.16. Just update the image: updating Homebrew takes
~2 minutes and slows down the CI a lot.
=> Run iOS tests against newer Go version

go.mod, go.sum
Pinning this module to a proper version as it was causing me issues due to the pretty old version of `x/sys` in `go.mod`. Tests are passing, vet is clean, and `fmt` is good.
=> Pin golang.org/x/sys

.github/workflows/build.yml, .github/workflows/test.yml
`actions/setup-go@v4` has been released.
- https://github.com/actions/setup-go/releases/tag/v4.0.0
=> bump actions/setup-go v4

CHANGELOG.md, backend_kqueue.go, fsnotify.go, fsnotify_test.go
There were two problems here:
- When we see a link inside a directory the resolved version would get added to w.watches etc. but the link won't, resulting in many spurious create events for the link. This fixes #277; I'm surprised there aren't more reports for this).
- filepath.EvalSymlinks() will resolve any symlinks in the entire path, rather than just the link itself. This would cause paths such as:
/path/to/LINK/dir/dir/WATCH-THIS
To have the wrong Event.Name; many of the test cases failed because of this because /tmp is a link to /private/tmp on macOS, but curiously no one reported it AFAIK (I guess many people don't use symlinks all that much).
Example:
% mkdir /tmp/xxx
% touch /tmp/xxx/FILE
% ln -s /tmp/xxx/LINK /tmp/xxx/FILE   # 25 years of Unix experience, and still...
ln: …
=> Fix symlink behaviour on kqueue

CHANGELOG.md, backend_fen.go, backend_inotify.go, backend_kqueue.go, backend_other.go, backend_windows.go, helpers_test.go, mkdoc.zsh
I don't really have the time to properly implement it for inotify, kqueue, and illumos, and it seems no one else has ether.
This will allow us to release a new version, which includes many bugfixes.
=> Remove the Windows "recursive" backend for now

.github/workflows/test.yml
=> Add back illumos

backend_fen.go, backend_inotify.go, backend_kqueue.go, backend_other.go, backend_windows.go, fsnotify_test.go, mkdoc.zsh
On Windows deleting the watched directive gives undefined results and delivering events for the files in the directory is not guaranteed. I can reproduce this even with a very simple example in Python, and it's not an fsnotify bug as far as I can see.
There's nothing we can do about this, so update the documentation and tweak the test so we don't get intermittent test failures.
On other platforms it does report all files.
=> Document and test removing watched directory on Windows

.github/workflows/test.yml, fsnotify_test.go
Use the new vmactions runners based on linux/qemu rather than
macos/vagrant. This should be much more stable and reliable.
Also switch the illumos VM to that, since they now have one, and add
DragonFlyBSD.
Remove the old Debian 6 test. It's broken and not all that useful to
have; maybe some systems want to use current versions of fsnotify on
very old Linux kernels, but I doubt it.
=> Update BSD vmactions

backend_kqueue.go, fsnotify_test.go
On macOS it seems that sometimes an event with Ident=0 is delivered, and
no other flags/information beyond that, even though we never saw such a
file descriptor. For example in TestWatchSymlink/277 (usually at the
end, but sometimes sooner):
CREATE               "/foo"
REMOVE               "/foo"
CREATE               "/apple"
CREATE               "/pear"
RENAME               "/apple"
REMOVE               "/pear"
WRITE                ""
Printing some debug in the loop right after we receive events shows:
unix.Kevent_t{Ident:0x2a, Filter:-4, Flags:0x25, Fflags:0x2, Data:0, Udata:(*uint8)(nil)}
unix.Kevent_t{Ident:0x0,  Filter:-4, Flags:0x25, Fflags:0x2, Data:0, Udata:(*uint8)(nil)}
The first is a normal event, the second with Ident 0. No error flag, no
data, no ... nothing.
I read a bit …
=> kqueue: ignore events with Ident=0

fsnotify_test.go
Seems to work now(?) This exception has been there for years, but now it consistently seems to fail both for me locally and in the CI (for example in #617). But on the main branch it worked just a few weeks ago(?)
And while the CI could have been updated, my local environment hasn't:
netbsd$ uname -a
NetBSD 9.2 (GENERIC) #0: Wed May 12 13:15:55 UTC 2021  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC
🤷
=> Fix CI on NetBSD

backend_kqueue.go
These file descriptors are being leaked to child processes because O_CLOEXEC isn't set.
=> kqueue: set O_CLOEXEC on close pipe fds

backend_fen.go, fsnotify_test.go
When watching /tmp, w.port.PathIsWatched(name) returned true for /tmp/abc. PathIsWatched() checks:
_, found := e.paths[path]
return found
That e.paths gets set in EventPort.AssociatePath(), which is called by Watcher.associateFile() for every path inside a watched directory. So it can never watch subpaths.
Anyway, this seems safe to remove. Could check our own Watcher.dirs state, but this doesn't seem needed (we already have tests for watching the same path more than once).
(This came rolling out of #620).
=> fen: allow watching subdirectories of watched directories

CHANGELOG.md, backend_kqueue.go, testdata/watch-symlink/to-dir, testdata/watch-symlink/to-file
When watching a symlink to a directory it would emit events with the target name, rather than the link name.
=> kqueue: emit events as "/path/dir/file" instead of "path/link/file"

internal/debug_kqueue.go, internal/debug_linux.go, internal/debug_solaris.go, internal/debug_windows.go
The only way we can convert a mask to something with meaningful names is by keeping a static list. That's fine, but flags we don't know would get silently dropped.
=> Print unknown flags with FSNOTIFY_DEBUG

backend_inotify.go, backend_windows.go, fsnotify.go, fsnotify_test.go, helpers_test.go, internal/debug_linux.go, internal/debug_windows.go, testdata/watch-dir/bug-277, testdata/watch-dir/rename-file, testdata/watch-dir/rename-from-other-watch, testdata/watch-dir/rename-from-unwatched-overwrite, testdata/watch-dir/rename-overwrite, testdata/watch-dir/rename-symlink, testdata/watch-file/overwrite-watched-file, testdata/watch-file/overwrite-watched-file-with-watched-file, testdata/watch-recurse/rename-dir
Add Event.RenamedFrom to track event renames; this is sent on a subsequent Create event; for example:
Event{Op: Rename, Name: "/tmp/file"}
Event{Op: Create, Name: "/tmp/renamed", RenamedFrom: "/tmp/file"}
For now this is unexported as renamedFrom because the kqueue and FEN backends are not yet implemented.
Updates #26
=> inotify, windows: track renames

CONTRIBUTING.md, backend_fen.go, backend_inotify.go, backend_kqueue.go, backend_other.go, backend_windows.go, cmd/fsnotify/closewrite.go, fsnotify.go, fsnotify_test.go, helpers_test.go, mkdoc.zsh, testdata/watch-dir/multiple-creates, testdata/watch-dir/only-chmod, testdata/watch-dir/only-create, testdata/watch-dir/only-remove, testdata/watch-dir/only-rename, testdata/watch-dir/only-write, testdata/watch-dir/op-all, testdata/watch-dir/op-closeread, testdata/watch-dir/op-closewrite, testdata/watch-dir/op-open, testdata/watch-dir/op-read, testdata/watch-file/op-all, testdata/watch-file/op-closeread, testdata/watch-file/op-closewrite, testdata/watch-file/op-open, testdata/watch-file/op-read
This adds the ability to only listen for some event types. If you're only interested in Created events and you're getting a lot of Write events then you're just wasting CPU cycles
This also adds the ability listen on extra unportable event types; since this is so related I figured I might as well do both. Ideally we want to 1) make it very very obvious you're doing something unportable, and 2) make it reasonably easy "fallback" for platforms where this isn't supported.
Unportable events start with "Unportable", which should document their unportabilitiness. Also add a new Supports(Op) method, which should make adding fallback logic relatively painless.
For example, to use CloseWrite where supported, but falling back to Write when it's not:
var op fsnotify.Op
if …
=> Support filtering events, add unsupported events

backend_inotify.go, fsnotify.go, helpers_test.go, testdata/watch-dir/symlink-nofollow, testdata/watch-symlink/nofollow-dir, testdata/watch-symlink/nofollow-file
Option to not follow symlinks, but watch the links themselves.
Unexported for now, until it's supported everywhere.
Updates #227
=> inotify: implement WithNoFollow()

backend_inotify.go, fsnotify.go, fsnotify_test.go, helpers_test.go, testdata/watch-recurse/add-dir, testdata/watch-recurse/remove-dir, testdata/watch-recurse/remove-recursive, testdata/watch-recurse/remove-watched-dir, testdata/watch-recurse/rename-dir
This adds a recursive watcher for inotify.
Updates:  #18
=> inotify: add recursive watcher

internal/ztest/diff_test.go
A tiny fix: the year 2024 is hard-coded in one of the tests, so that it fails in The Year of the Linux Desktop.
=> Fix hardcoded year in test

backend_fen.go, backend_inotify.go, backend_kqueue.go, fsnotify_test.go, helpers_test.go
It would access "watch.wd", but that's racy. I redid quite a bit of the inotify backend to add some new features, so regression from one of those changes (and/or would work "by accident" before).
Fixes #653
Fixes #664
Fixes #672
=> Fix race in inotify backend

backend_inotify.go, fsnotify_test.go, testdata/watch-dir/remove-symlink
inotify_add_watch() follows symlinks, and returns the current watch descriptor when adding a patch twice. So when doing "watch dir" and "watch link" (or reverse) second watch is basically a no-op; yet it's still registered as a "separate" watch, and would panic on removing the second.
The solution is to make the second Add() a no-op. This is also what kqueue does, and what happens if you watch the same path twice.
On illumos watching a symlink currently means registering double watches; this is a separate bug that should be fixed.
Fixes #652
Fixes #662
=> Don't add double watches for symlinks

backend_kqueue.go, testdata/watch-dir/create-cyclic-symlink, testdata/watch-dir/create-file-in-subdir, testdata/watch-dir/symlink-dir, testdata/watch-symlink/to-dir-relative, testdata/watch-symlink/to-file-relative
Also only resolve symlinks explicitly given in Add()/AddWith(), and not those added "internally" as part of a listdir. Also don't ignore errors from os.Readlink() and os.Lstat; this was added in 2012 with bf36090 to ignore unresolvable symlinks when listing a directory, but we're no longer calling lstat() on the result of a link unless it's explicitly passed with Add().
Fixes #661
=> Fix relative links on kqueue

backend_kqueue.go, testdata/watch-symlink/to-dir
It would mark /dir/existing as seen, but would check for /link/existing. So on the first change in a directory it would list all pre-existing entries in the directory.
Regression from d2ee00e; just wasn't a testcase.
=> Correctly mark pre-existing entries when watching a link to a dir on kqueue

.github/workflows/test.yml
Normally tests take 3 to 4 minutes at the most, for the tests that use a QEMU VM. But sometimes either a test or booting the VM will hang. Fail faster on this.
=> Add timeout-minutes in GitHub actions

fsnotify.go, fsnotify_test.go
Taken from a branch I worked on some time ago where this was a bug.
=> Add test to ensure Add()/Remove() works when not reading events

.github/workflows/test.yml, CHANGELOG.md, backend_fen.go, backend_kqueue.go, cmd/fsnotify/main.go, fsnotify.go, fsnotify_test.go, go.mod, internal/darwin.go, internal/freebsd.go, internal/unix.go, internal/unix2.go, internal/windows.go, internal/ztest/diff.go, internal/ztest/diff_test.go
We can use generic for our helper and remove the rlimit stuff (as that's done automatically since Go 1.19).
=> Use Go 1.19, add ignoringEINTR helper

README.md, fsnotify.go
Since Linux 5.11-rc1, fs.inotify.max_user_watches is dynamically computed up to 1048576 with regards to the addressable physical memory: https://github.com/torvalds/linux/commit/92890123749bafc317bbfacbe0a62ce08d78efb7 .
=> Remove explicit sysctl fs.inotify.max_user_watches hardcoding suggestion
