- README.md
- circle.yml
- example_test.go
This isn't working yet. Even reverting to the [example in the docs](https://circleci.com/docs/ios#custom-packages) doesn't work. Waiting for support.
> setup CircleCI to test on OS X

- windows.go
fix #151
I only tested on Windows. 3 of the 4 changes are covered by tests. Not sure if I should had a test for the fourth one or not.
I think I signed the CLA a while ago.
> Use filepath.Join()

- inotify_test.go
Add a missing %v to a format string
N/A
Not necessary.
Note: I have signed the CLA
> Fix missing verb on format string

- inotify_poller.go
- open_mode_bsd.go
- open_mode_darwin.go
> Open files with CLOEXEC

- .github/workflows/test.yml
Updates the test matrix in light of the release of Go 1.17
Check that CI ran successfully.
Shouldn't be needed.
> Update test matrix for go 1.17 stable release

- .github/workflows/build.yml
Similar to #415 except this is just the cross-compilation builds which are even faster than the tests.
Rationale of #415 
N/A
> Enable cross-compilation builds on PRs

- fsnotify_unsupported.go
> Fix compilation for OpenBSD

- go.mod
- go.sum
This version contains several upgrades including a newer version of
glibc and some bug fixes.
> go.mod: use latest x/sys

- windows.go
> Windows: add missing defer to Watcher.WatchList

- .github/workflows/build.yml
- .github/workflows/test.yml
- bump actions/setup-go from v2 to v3
- bump actions/checkout from v2 to v3
- bump vmactions/freebsd-vm from v0.1.5 to v0.2.0
See the results of GitHub Actions
> bump up GitHub Actions

- CHANGELOG.md
Just copied from the releases page: https://github.com/fsnotify/fsnotify/releases
Fixes #332
> Add missing changelog for 1.4.{8,9}

- fsnotify.go
Clarify what "relative" means here.
Fixes #362
> Tweak comment regarding relative paths

- .github/workflows/test.yml
Doesn't really test anything yet, but should do soon.
> Run tests in illumos

- windows.go
Specifically to address https://github.com/fsnotify/fsnotify/issues/364; syscall.GetQueuedCompletionStatus()
contains a bug that can't be fixed in a backwards-compatible way, so
they didn't. Once you use sys/windows for one thing, you gotta use it
for everything.
I ran the tests with -count=100 locally, and it all seems fine.
While I'm here, also replace "e" with "err" for error variables.
The way it was used now was sometimes also confusing.
Fixes https://github.com/fsnotify/fsnotify/issues/364
> windows: replace syscall with golang.org/x/sys/windows

- inotify.go
- kqueue.go
- windows.go
Add a helper function instead of doing a select on w.done and w.Errors
or w.Events every time.
Also move most functions to methods on the Watcher.
> Add Watcher.{sendEvent,sendError}

- windows.go
The sys* constants were used in the old golang.org/x/exp/winfsnotify
package on which this is based, but haven't been in use for a long time.
Remove the "one shot", "dir only", and "ignore" options as they were
never set. Also don't send "sysFSQOVERFLOW" as an event if the buffer is
too long; we already send an error and it's just a weird magical number
you get.
This could be simplified greatly more by removing the whole
sysFS… → windows.FILE_NOTIFY… → sysFS… conversions, but that's for
another day.
> windows: simplify a bit

- fsnotify_test.go
> Add test for re-adding a renamed file

- .github/workflows/test.yml
> Run gccgo in CI

- fsnotify_test.go
> Test Add() on non-existent path

- .cirrus.yml
- .github/workflows/build.yml
- .github/workflows/test.yml
- backend_kqueue.go
The fi gets referenced in the error handler for getting it.
> Fix nil derefence panic 

- backend_windows.go
- fsnotify_test.go
> Fix behavior of WatchList for Windows

- backend_fen.go
> Remove unnecessary code duplication

- CHANGELOG.md
- backend_inotify.go
- fsnotify_test.go
This would result in two events being sent.
> inotify: don't send event for IN_DELETE_SELF when also watching the parent

- .gitignore
- CHANGELOG.md
- backend_fen.go
- backend_inotify.go
- backend_kqueue.go
- backend_kqueue_test.go
- backend_windows.go
- testdata/watch-dir/bug-277
- testdata/watch-symlink/to-dir-relative
- testdata/watch-symlink/to-file-relative
This simplifies things quite a bit.
Previous: #543
> kqueue: simplify bookkeeping of watched paths

- backend_fen_test.go
- backend_inotify_test.go
- backend_kqueue.go
- backend_kqueue_test.go
- backend_windows_test.go
> kqueue: don't change internal state when Add() returns error

- backend_inotify.go
- fsnotify_test.go
It would do:
events := read_events_from_kernel()
for _, e := range events {
watch := read_our_state(e)
do_stuff_with(watch)
}
However, between read_events_from_kernel() and read_our_state() the internal state could have been removed with Watcher.Remove() in another goroutine, so it would return nil.
In many cases it already did "if watch != nil && [..]" to deal with this, but not everywhere. Do an "early continue" instead.
Fixes #616
---
Ideally what it should do is block any Remove() for all of the above code, so it always operates on a consistent state. But that's not so easy to do in a quick fix, and I don't really have the time to spend on this at the moment (and it seems no one else has either).
> inotify: fix panic on Remove()
